# Generated by Django 5.2.6 on 2025-10-21 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_remove_asignacion_fecha_asignacion_and_more'),
        ('entrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='asignacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.asignacion'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
    ]
