# Generated by Django 5.2.6 on 2025-10-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0003_rename_evaluacion_diagnostico'),
        ('entrega', '0002_alter_entrega_asignacion_alter_entrega_estado'),
    ]

    
