# Generated by Django 5.2.6 on 2025-10-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0003_rename_evaluacion_diagnostico'),
        ('entrega', '0003_rename_entrega_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='asignacion',
        ),
        migrations.AddField(
            model_name='reporte',
            name='diagnostico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostico.diagnostico'),
        ),
    ]
