# Generated by Django 5.2.6 on 2025-10-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
