# Generated by Django 5.2.6 on 2025-10-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('problema', models.TextField()),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
