# Generated by Django 5.2.6 on 2025-10-21 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='fecha_asignacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='fecha_evaluacion',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcion.equipo'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.estudiante'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='asignacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.asignacion'),
        ),
    ]
