# Generated by Django 5.2.6 on 2025-10-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_remove_asignacion_fecha_asignacion_and_more'),
    ]

